# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='project',
        ),
    ]
