# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20170218_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
