# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-18 22:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_project_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='archivo',
            field=models.FileField(default=datetime.datetime(2017, 2, 18, 22, 17, 23, 492584, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
