# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_base_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Down',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('project_name', models.CharField(max_length=250)),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='base',
            name='archivo',
            field=models.FileField(upload_to=''),
        ),
    ]
