# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20170220_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='down',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='down',
            old_name='project_name',
            new_name='proyecto',
        ),
        migrations.RemoveField(
            model_name='down',
            name='archivo',
        ),
    ]
