# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20170220_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poligono', models.CharField(choices=[('poligono', 'Poligono')], default='poligono', max_length=50)),
                ('manzana', models.CharField(choices=[('iquique', '01_Iquique_AltoHospicio_poligono')], default='iquique', max_length=50)),
                ('archivo', models.CharField(choices=[('shapefile', 'Shapefile')], default='shapefile', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='update', max_length=50)),
                ('nombre_proyecto', models.CharField(max_length=250)),
                ('razon_de_carga', models.CharField(max_length=250)),
                ('tipo_de_datos', models.CharField(choices=[('shapefile', 'Shapefile')], default='shapefile', max_length=250)),
                ('unidad_regional', models.CharField(max_length=250)),
                ('comentarios', models.CharField(max_length=250)),
                ('archivo', models.FileField(upload_to='media/')),
            ],
        ),
    ]
