# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-10 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_mymodel_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploader',
            name='unidad_regional',
        ),
        migrations.AddField(
            model_name='uploader',
            name='unidad_territorial',
            field=models.CharField(choices=[('region', 'Region'), ('provincia', 'Provincia'), ('comuna', 'Comuna'), ('distrito', 'Distrito'), ('manzana', 'Manzana')], default='region', max_length=100),
        ),
    ]
