# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_auto_20170410_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_paquetes', models.CharField(choices=[('R1', 'Region 1'), ('R2', 'Region 2'), ('R3', 'Region 3'), ('R4', 'Region 4'), ('R5', 'Region 5')], default='R1', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tags', models.CharField(max_length=250)),
            ],
        ),
    ]
