# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_paquetes_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquetes2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_paquetes', models.CharField(choices=[('R1', 'Region 1'), ('R2', 'Region 2'), ('R3', 'Region 3'), ('R4', 'Region 4'), ('R5', 'Region 5')], default='R1', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='paquetes',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
