# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20170503_0605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paquetes2',
        ),
    ]
