# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_delete_paquetes2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquetes',
            name='name',
        ),
        migrations.AddField(
            model_name='paquetes',
            name='tipo_de_datos',
            field=models.CharField(choices=[('shapefile', 'Shapefile'), ('csv', 'CSV')], default='shapefile', max_length=250),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='tipo_de_datos',
            field=models.CharField(choices=[('shapefile', 'Shapefile'), ('csv', 'CSV')], default='shapefile', max_length=250),
        ),
    ]
