# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0016_auto_20170503_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquetes',
            name='tipo_de_datos',
        ),
    ]
