# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-05 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_remove_paquetes_tipo_de_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetes',
            name='name',
            field=models.CharField(choices=[('shapefile', 'Shapefile'), ('csv', 'CSV')], default='shapefile', max_length=250),
        ),
    ]
